#!/system/bin/sh

if [ -e /data/local/scriptlog.txt ];then
rm /data/local/scriptlog.txt
fi
SCRIPTLOG=/data/local/scriptlog.txt
touch $SCRIPTLOG
echo "$(date) Log Created..." >> $SCRIPTLOG
if [ -e /system/etc/init.d ];then
  for i in /system/etc/init.d/* ; do
        echo "$(date) $i Started.." >> $SCRIPTLOG
        $i  2>>$SCRIPTLOG 
        echo "$(date) $i Finished.." >> $SCRIPTLOG
  done
fi
